=== hmrc/individuals-if-api-stub/resources/public/api/conf/1.0/schemas/organisations/create-corporation-tax-company-detail.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Organisations corporation-tax details",
  "type": "object",
  "required": ["utr", "registeredDetails", "communicationDetails"],
  "properties": {
    "utr": {
      "type": "string",
      "example": "1234567890",
      "pattern": "^[0-9]{10}$",
      "description": "A Unique Tax Reference"
    },
    "crn": {
      "type": "string",
      "example": "12345678",
      "pattern": "^[A-Z0-9]{1,10}$",
      "description": "Company Reference Number"
    },
    "registeredDetails": {
      "type": "object",
      "properties": {
        "name": {
          "type": "object",
          "properties": {
            "name1": {
              "type": "string",
              "example": "Waitrose"
            },
            "name2": {
              "type": "string",
              "example": "And Partners"
            }
          }
        },
        "address": {
          "type": "object",
          "properties": {
            "line1": {
              "type": "string",
              "example": "Alfie House"
            },
            "line2": {
              "type": "string",
              "example": "Main Street"
            },
            "line3": {
              "type": "string",
              "example": "Manchester"
            },
            "line4": {
              "type": "string",
              "example": "Londonberry"
            },
            "postcode": {
              "type": "string",
              "example": "LN1 1AG"
            }
          }
        }
      }
    },
    "communicationDetails": {
      "type": "object",
      "properties": {
        "name": {
          "type": "object",
          "properties": {
            "name1": {
              "type": "string",
              "example": "Waitrose"
            },
            "name2": {
              "type": "string",
              "example": "And Partners"
            }
          }
        },
        "address": {
          "type": "object",
          "properties": {
            "line1": {
              "type": "string",
              "example": "Orange House"
            },
            "line2": {
              "type": "string",
              "example": "Corporation Street"
            },
            "line3": {
              "type": "string",
              "example": "London"
            },
            "line4": {
              "type": "string",
              "example": "Londonberry"
            },
            "postcode": {
              "type": "string",
              "example": "LN1 1AG"
            }
          }
        }
      }
    }
  }
}

=== hmrc/individuals-if-api-stub/resources/public/api/conf/1.0/examples/organisations/create-corporation-tax-company-detail.json
{
  "utr": "1234567890",
  "crn": "12345678",
  "registeredDetails": {
    "name": {
      "name1": "Waitrose",
      "name2": "And Partners"
    },
    "address": {
      "line1": "Alfie House",
      "line2": "Main Street",
      "line3": "Manchester",
      "line4": "Londonberry",
      "postcode": "LN1 1AG"
    }
  },
  "communicationDetails": {
    "name": {
      "name1": "Waitrose",
      "name2": "And Partners"
    },
    "address": {
      "line1": "Orange House",
      "line2": "Corporation Street",
      "line3": "London",
      "line4": "Londonberry",
      "postcode": "LN1 1AG"
    }
  }
}
