=== hmrc/individuals-if-api-stub/resources/public/api/conf/1.0/schemas/organisations/create-corporation-tax-detail.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Organisations return details",
  "type": "object",
  "required": ["utr", "accountingPeriods"],
  "properties": {
    "utr": {
      "type": "string",
      "example": "1234567890",
      "description": "A Unique Tax Reference"
    },
    "taxpayerStartDate": {
      "id": "full-date",
      "example": "2015-04-21",
      "description": "The taxpayer start date."
    },
    "taxSolvencyStatus": {
      "type": "string",
      "example": "V",
      "description": "The tax solvency status."
    },
    "accountingPeriods": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["turnover"],
        "properties": {
          "apStartDate" : {
            "id": "full-date",
            "example": "2018-04-06"
          },
          "apEndDate" : {
            "id": "full-date",
            "example": "2018-10-05"
          },
          "turnover": {
            "type": "integer",
            "example": "38390",
            "description": "Turnover."
          }
        }
      }
    }
  }
}

=== hmrc/individuals-if-api-stub/resources/public/api/conf/1.0/examples/organisations/create-corporation-tax-detail.json
{
  "utr": "1234567890",
  "taxpayerStartDate": "2015-04-21",
  "taxSolvencyStatus": "V",
  "accountingPeriods": [
    {
      "apStartDate": "2018-04-06",
      "apEndDate": "2018-10-05",
      "turnover": 38390
    },
    {
      "apStartDate": "2018-10-06",
      "apEndDate": "2019-04-05",
      "turnover": 2340
    }
  ]
}
