=== hmrc/individuals-if-api-stub/resources/public/api/conf/1.0/schemas/organisations/create-organisations-return-detail.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Organisations return details",
  "type": "object",
  "required": [
    "utr",
    "startDate",
    "taxpayerType",
    "taxSolvencyStatus",
    "taxyears"
  ],
  "properties": {
    "utr": {
      "type": "string",
      "description": "A Unique Tax Reference Number",
      "pattern": "^[0-9]{10}$",
      "example": "1234567890"
    },
    "startDate": {
      "type": "string",
      "description": "Start date",
      "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$",
      "example" : "2015-04-21"
    },
    "taxpayerType": {
      "type": "string",
      "description": "Taxpayer Type",
      "pattern": "^[A-Z][a-zA-Z]{3,24}$",
      "example" : "Individual"
    },
    "taxSolvencyStatus": {
      "type": "string",
      "enum": ["S", "I"],
      "description": "The Tax Solvency Status. Should be 1 character",
      "example": "S"
    },
    "taxyears": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "taxyear": {
            "type": "integer",
            "example": "2020",
            "pattern": "^20[0-9]{2}$",
            "description": "The tax year"
          },
          "businessSalesTurnover": {
            "type": "number",
            "example": "20177.77",
            "description": "The business sales turnover"
          }
        }
      }
    }
  }
}

=== hmrc/individuals-if-api-stub/resources/public/api/conf/1.0/examples/organisations/create-organisations-return-detail.json
{
  "utr": "1234567890",
  "taxpayerType": "Individual",
  "startDate": "2015-04-21",
  "taxSolvencyStatus": "S",
  "taxyears": [
    {
      "taxYear": "2020",
      "businessSalesTurnover": 38390.76
    },
    {
      "taxYear": "2019",
      "businessSalesTurnover": 12343.12
    },
    {
      "taxYear": "2018",
      "businessSalesTurnover": 20182.22
    },
    {
      "taxYear": "2017",
      "businessSalesTurnover": 20177.77
    },
    {
      "taxYear": "2016",
      "businessSalesTurnover": 20166.66
    },
    {
      "taxYear": "2015",
      "businessSalesTurnover": 20155.55
    },
    {
      "taxYear": "2014",
      "businessSalesTurnover": 20144.50
    }
  ]
}
